//
// AUTOGENERATED CODE. DO NOT EDIT MANUALLY.
// REFER TO Tools/Blade.DiagnosticGen/Program.cs TO EDIT FILE.
//
#nullable enable

using Blade;
using Blade.Source;

namespace Blade.Diagnostics;

public abstract partial class DiagnosticMessage
{
    public static (DiagnosticSeverity severity, int code)? GetByName(string name)
    {
        return name switch
        {
            "UnexpectedCharacter" => (DiagnosticSeverity.Error, 1),
            "UnterminatedString" => (DiagnosticSeverity.Error, 2),
            "InvalidNumberLiteral" => (DiagnosticSeverity.Error, 3),
            "UnterminatedBlockComment" => (DiagnosticSeverity.Error, 4),
            "InvalidCharacterLiteral" => (DiagnosticSeverity.Error, 5),
            "InvalidEscapeSequence" => (DiagnosticSeverity.Error, 6),
            "InvalidUtf8" => (DiagnosticSeverity.Error, 7),
            "InvalidControlCharacter" => (DiagnosticSeverity.Error, 8),
            "UnexpectedToken" => (DiagnosticSeverity.Error, 101),
            "ExpectedExpression" => (DiagnosticSeverity.Error, 102),
            "ExpectedStatement" => (DiagnosticSeverity.Error, 103),
            "ExpectedTypeName" => (DiagnosticSeverity.Error, 104),
            "ExpectedIdentifier" => (DiagnosticSeverity.Error, 105),
            "InvalidAssignmentTarget" => (DiagnosticSeverity.Error, 106),
            "ExpectedSemicolon" => (DiagnosticSeverity.Error, 107),
            "DuplicateVariableClause" => (DiagnosticSeverity.Error, 108),
            "SymbolAlreadyDeclared" => (DiagnosticSeverity.Error, 201),
            "UndefinedName" => (DiagnosticSeverity.Error, 202),
            "UndefinedType" => (DiagnosticSeverity.Error, 203),
            "CannotAssignToConstant" => (DiagnosticSeverity.Error, 204),
            "TypeMismatch" => (DiagnosticSeverity.Error, 205),
            "NotCallable" => (DiagnosticSeverity.Error, 206),
            "ArgumentCountMismatch" => (DiagnosticSeverity.Error, 207),
            "InvalidLoopControl" => (DiagnosticSeverity.Error, 208),
            "InvalidBreakInRepLoop" => (DiagnosticSeverity.Error, 209),
            "InvalidYieldUsage" => (DiagnosticSeverity.Error, 210),
            "InvalidYieldtoUsage" => (DiagnosticSeverity.Error, 211),
            "ReturnValueCountMismatch" => (DiagnosticSeverity.Error, 212),
            "ReturnOutsideFunction" => (DiagnosticSeverity.Error, 213),
            "InvalidYieldtoTarget" => (DiagnosticSeverity.Error, 214),
            "InvalidLocalStorageClass" => (DiagnosticSeverity.Error, 215),
            "InvalidExternScope" => (DiagnosticSeverity.Error, 216),
            "InvalidParameterStorageClass" => (DiagnosticSeverity.Error, 217),
            "PointerStorageClassRequired" => (DiagnosticSeverity.Error, 264),
            "UnknownNamedArgument" => (DiagnosticSeverity.Error, 219),
            "DuplicateNamedArgument" => (DiagnosticSeverity.Error, 220),
            "PositionalArgumentAfterNamed" => (DiagnosticSeverity.Error, 221),
            "NamedArgumentConflictsWithPositional" => (DiagnosticSeverity.Error, 222),
            "InvalidAddressOfTarget" => (DiagnosticSeverity.Error, 223),
            "InvalidExplicitCast" => (DiagnosticSeverity.Error, 224),
            "BitcastSizeMismatch" => (DiagnosticSeverity.Error, 225),
            "AddressOfRecursiveLocal" => (DiagnosticSeverity.Error, 226),
            "MissingReturnValue" => (DiagnosticSeverity.Error, 227),
            "ReturnFromCoroutine" => (DiagnosticSeverity.Error, 278),
            "FileImportAliasRequired" => (DiagnosticSeverity.Error, 228),
            "UnknownNamedModule" => (DiagnosticSeverity.Error, 229),
            "ImportFileNotFound" => (DiagnosticSeverity.Error, 230),
            "CircularImport" => (DiagnosticSeverity.Error, 231),
            "EnumLiteralRequiresContext" => (DiagnosticSeverity.Error, 232),
            "BitfieldWidthOverflow" => (DiagnosticSeverity.Error, 233),
            "ArrayLiteralRequiresContext" => (DiagnosticSeverity.Error, 234),
            "ArrayLiteralSpreadMustBeLast" => (DiagnosticSeverity.Error, 235),
            "StructUnknownField" => (DiagnosticSeverity.Error, 236),
            "StructMissingFields" => (DiagnosticSeverity.Error, 237),
            "StructDuplicateField" => (DiagnosticSeverity.Error, 238),
            "StringLengthMismatch" => (DiagnosticSeverity.Error, 239),
            "StringToNonConstPointer" => (DiagnosticSeverity.Error, 240),
            "ComptimeValueRequired" => (DiagnosticSeverity.Error, 241),
            "ComptimeUnsupportedConstruct" => (DiagnosticSeverity.Error, 242),
            "ComptimeForbiddenSymbolAccess" => (DiagnosticSeverity.Error, 243),
            "ComptimeFuelExhausted" => (DiagnosticSeverity.Error, 244),
            "DuplicateNamedModuleRoot" => (DiagnosticSeverity.Error, 245),
            "MultiAssignmentRequiresCall" => (DiagnosticSeverity.Error, 246),
            "MultiAssignmentTargetCountMismatch" => (DiagnosticSeverity.Error, 247),
            "DiscardInExpression" => (DiagnosticSeverity.Error, 248),
            "ExternCannotHaveInitializer" => (DiagnosticSeverity.Error, 249),
            "MemoryofRequiresVariable" => (DiagnosticSeverity.Error, 250),
            "QueryRequiresMemorySpace" => (DiagnosticSeverity.Error, 251),
            "QueryUnsupportedType" => (DiagnosticSeverity.Error, 252),
            "QueryAutomaticLocal" => (DiagnosticSeverity.Error, 253),
            "InvalidMemorySpaceArgument" => (DiagnosticSeverity.Error, 254),
            "AssertionFailed" => (DiagnosticSeverity.Error, 255),
            "UnknownBuiltin" => (DiagnosticSeverity.Error, 256),
            "InvalidPointerArithmetic" => (DiagnosticSeverity.Error, 257),
            "IncompatiblePointerSubtraction" => (DiagnosticSeverity.Error, 258),
            "ExpressionNotAStatement" => (DiagnosticSeverity.Error, 259),
            "RangeIterationRequiresBinding" => (DiagnosticSeverity.Error, 260),
            "RangeExpressionOutsideForLoop" => (DiagnosticSeverity.Error, 263),
            "ComptimeIntegerTruncation" => (DiagnosticSeverity.Warning, 261),
            "AddressOfParameter" => (DiagnosticSeverity.Error, 262),
            "AmbiguousLayoutMemberAccess" => (DiagnosticSeverity.Error, 265),
            "LexicalNameConflictsWithLayoutMember" => (DiagnosticSeverity.Warning, 266),
            "LayoutMemberShadowsParentMember" => (DiagnosticSeverity.Warning, 267),
            "TaskLayoutCannotBeInherited" => (DiagnosticSeverity.Error, 268),
            "InvalidSpawnTarget" => (DiagnosticSeverity.Error, 279),
            "MainTaskMustBeCog" => (DiagnosticSeverity.Warning, 269),
            "MissingMainTask" => (DiagnosticSeverity.Error, 270),
            "FunctionLayoutSubsetViolation" => (DiagnosticSeverity.Error, 271),
            "DuplicateFunctionLayoutMetadata" => (DiagnosticSeverity.Warning, 272),
            "DuplicateFunctionAlignMetadata" => (DiagnosticSeverity.Error, 273),
            "InvalidFunctionAlignment" => (DiagnosticSeverity.Error, 274),
            "TaskLayoutNotAllowedInFunctionMetadata" => (DiagnosticSeverity.Error, 275),
            "AccessToForeignLayout" => (DiagnosticSeverity.Error, 276),
            "UnsupportedGlobalStorage" => (DiagnosticSeverity.Error, 277),
            "InvalidLayoutAlignment" => (DiagnosticSeverity.Error, 280),
            "InvalidLayoutAddress" => (DiagnosticSeverity.Error, 281),
            "LayoutAddressConflict" => (DiagnosticSeverity.Error, 282),
            "LayoutAllocationFailed" => (DiagnosticSeverity.Error, 283),
            "InlineAsmUnknownInstruction" => (DiagnosticSeverity.Error, 301),
            "InlineAsmUndefinedVariable" => (DiagnosticSeverity.Error, 302),
            "InlineAsmEmptyInstruction" => (DiagnosticSeverity.Error, 303),
            "InlineAsmInvalidFlagOutput" => (DiagnosticSeverity.Error, 304),
            "InlineAsmInvalidInstructionForm" => (DiagnosticSeverity.Error, 305),
            "InlineAsmUndefinedLabel" => (DiagnosticSeverity.Error, 306),
            "InlineAsmTempReadBeforeWrite" => (DiagnosticSeverity.Warning, 307),
            "UnsupportedLowering" => (DiagnosticSeverity.Error, 401),
            _ => null,
        };
    }

    public static string? GetNameFrom(int code)
    {
        return code switch
        {
            1 => "UnexpectedCharacter",
            2 => "UnterminatedString",
            3 => "InvalidNumberLiteral",
            4 => "UnterminatedBlockComment",
            5 => "InvalidCharacterLiteral",
            6 => "InvalidEscapeSequence",
            7 => "InvalidUtf8",
            8 => "InvalidControlCharacter",
            101 => "UnexpectedToken",
            102 => "ExpectedExpression",
            103 => "ExpectedStatement",
            104 => "ExpectedTypeName",
            105 => "ExpectedIdentifier",
            106 => "InvalidAssignmentTarget",
            107 => "ExpectedSemicolon",
            108 => "DuplicateVariableClause",
            201 => "SymbolAlreadyDeclared",
            202 => "UndefinedName",
            203 => "UndefinedType",
            204 => "CannotAssignToConstant",
            205 => "TypeMismatch",
            206 => "NotCallable",
            207 => "ArgumentCountMismatch",
            208 => "InvalidLoopControl",
            209 => "InvalidBreakInRepLoop",
            210 => "InvalidYieldUsage",
            211 => "InvalidYieldtoUsage",
            212 => "ReturnValueCountMismatch",
            213 => "ReturnOutsideFunction",
            214 => "InvalidYieldtoTarget",
            215 => "InvalidLocalStorageClass",
            216 => "InvalidExternScope",
            217 => "InvalidParameterStorageClass",
            264 => "PointerStorageClassRequired",
            219 => "UnknownNamedArgument",
            220 => "DuplicateNamedArgument",
            221 => "PositionalArgumentAfterNamed",
            222 => "NamedArgumentConflictsWithPositional",
            223 => "InvalidAddressOfTarget",
            224 => "InvalidExplicitCast",
            225 => "BitcastSizeMismatch",
            226 => "AddressOfRecursiveLocal",
            227 => "MissingReturnValue",
            278 => "ReturnFromCoroutine",
            228 => "FileImportAliasRequired",
            229 => "UnknownNamedModule",
            230 => "ImportFileNotFound",
            231 => "CircularImport",
            232 => "EnumLiteralRequiresContext",
            233 => "BitfieldWidthOverflow",
            234 => "ArrayLiteralRequiresContext",
            235 => "ArrayLiteralSpreadMustBeLast",
            236 => "StructUnknownField",
            237 => "StructMissingFields",
            238 => "StructDuplicateField",
            239 => "StringLengthMismatch",
            240 => "StringToNonConstPointer",
            241 => "ComptimeValueRequired",
            242 => "ComptimeUnsupportedConstruct",
            243 => "ComptimeForbiddenSymbolAccess",
            244 => "ComptimeFuelExhausted",
            245 => "DuplicateNamedModuleRoot",
            246 => "MultiAssignmentRequiresCall",
            247 => "MultiAssignmentTargetCountMismatch",
            248 => "DiscardInExpression",
            249 => "ExternCannotHaveInitializer",
            250 => "MemoryofRequiresVariable",
            251 => "QueryRequiresMemorySpace",
            252 => "QueryUnsupportedType",
            253 => "QueryAutomaticLocal",
            254 => "InvalidMemorySpaceArgument",
            255 => "AssertionFailed",
            256 => "UnknownBuiltin",
            257 => "InvalidPointerArithmetic",
            258 => "IncompatiblePointerSubtraction",
            259 => "ExpressionNotAStatement",
            260 => "RangeIterationRequiresBinding",
            263 => "RangeExpressionOutsideForLoop",
            261 => "ComptimeIntegerTruncation",
            262 => "AddressOfParameter",
            265 => "AmbiguousLayoutMemberAccess",
            266 => "LexicalNameConflictsWithLayoutMember",
            267 => "LayoutMemberShadowsParentMember",
            268 => "TaskLayoutCannotBeInherited",
            279 => "InvalidSpawnTarget",
            269 => "MainTaskMustBeCog",
            270 => "MissingMainTask",
            271 => "FunctionLayoutSubsetViolation",
            272 => "DuplicateFunctionLayoutMetadata",
            273 => "DuplicateFunctionAlignMetadata",
            274 => "InvalidFunctionAlignment",
            275 => "TaskLayoutNotAllowedInFunctionMetadata",
            276 => "AccessToForeignLayout",
            277 => "UnsupportedGlobalStorage",
            280 => "InvalidLayoutAlignment",
            281 => "InvalidLayoutAddress",
            282 => "LayoutAddressConflict",
            283 => "LayoutAllocationFailed",
            301 => "InlineAsmUnknownInstruction",
            302 => "InlineAsmUndefinedVariable",
            303 => "InlineAsmEmptyInstruction",
            304 => "InlineAsmInvalidFlagOutput",
            305 => "InlineAsmInvalidInstructionForm",
            306 => "InlineAsmUndefinedLabel",
            307 => "InlineAsmTempReadBeforeWrite",
            401 => "UnsupportedLowering",
            _ => null,
        };
    }

    public static DiagnosticSeverity? GetSeverity(int code)
    {
        return code switch
        {
            1 => DiagnosticSeverity.Error,
            2 => DiagnosticSeverity.Error,
            3 => DiagnosticSeverity.Error,
            4 => DiagnosticSeverity.Error,
            5 => DiagnosticSeverity.Error,
            6 => DiagnosticSeverity.Error,
            7 => DiagnosticSeverity.Error,
            8 => DiagnosticSeverity.Error,
            101 => DiagnosticSeverity.Error,
            102 => DiagnosticSeverity.Error,
            103 => DiagnosticSeverity.Error,
            104 => DiagnosticSeverity.Error,
            105 => DiagnosticSeverity.Error,
            106 => DiagnosticSeverity.Error,
            107 => DiagnosticSeverity.Error,
            108 => DiagnosticSeverity.Error,
            201 => DiagnosticSeverity.Error,
            202 => DiagnosticSeverity.Error,
            203 => DiagnosticSeverity.Error,
            204 => DiagnosticSeverity.Error,
            205 => DiagnosticSeverity.Error,
            206 => DiagnosticSeverity.Error,
            207 => DiagnosticSeverity.Error,
            208 => DiagnosticSeverity.Error,
            209 => DiagnosticSeverity.Error,
            210 => DiagnosticSeverity.Error,
            211 => DiagnosticSeverity.Error,
            212 => DiagnosticSeverity.Error,
            213 => DiagnosticSeverity.Error,
            214 => DiagnosticSeverity.Error,
            215 => DiagnosticSeverity.Error,
            216 => DiagnosticSeverity.Error,
            217 => DiagnosticSeverity.Error,
            264 => DiagnosticSeverity.Error,
            219 => DiagnosticSeverity.Error,
            220 => DiagnosticSeverity.Error,
            221 => DiagnosticSeverity.Error,
            222 => DiagnosticSeverity.Error,
            223 => DiagnosticSeverity.Error,
            224 => DiagnosticSeverity.Error,
            225 => DiagnosticSeverity.Error,
            226 => DiagnosticSeverity.Error,
            227 => DiagnosticSeverity.Error,
            278 => DiagnosticSeverity.Error,
            228 => DiagnosticSeverity.Error,
            229 => DiagnosticSeverity.Error,
            230 => DiagnosticSeverity.Error,
            231 => DiagnosticSeverity.Error,
            232 => DiagnosticSeverity.Error,
            233 => DiagnosticSeverity.Error,
            234 => DiagnosticSeverity.Error,
            235 => DiagnosticSeverity.Error,
            236 => DiagnosticSeverity.Error,
            237 => DiagnosticSeverity.Error,
            238 => DiagnosticSeverity.Error,
            239 => DiagnosticSeverity.Error,
            240 => DiagnosticSeverity.Error,
            241 => DiagnosticSeverity.Error,
            242 => DiagnosticSeverity.Error,
            243 => DiagnosticSeverity.Error,
            244 => DiagnosticSeverity.Error,
            245 => DiagnosticSeverity.Error,
            246 => DiagnosticSeverity.Error,
            247 => DiagnosticSeverity.Error,
            248 => DiagnosticSeverity.Error,
            249 => DiagnosticSeverity.Error,
            250 => DiagnosticSeverity.Error,
            251 => DiagnosticSeverity.Error,
            252 => DiagnosticSeverity.Error,
            253 => DiagnosticSeverity.Error,
            254 => DiagnosticSeverity.Error,
            255 => DiagnosticSeverity.Error,
            256 => DiagnosticSeverity.Error,
            257 => DiagnosticSeverity.Error,
            258 => DiagnosticSeverity.Error,
            259 => DiagnosticSeverity.Error,
            260 => DiagnosticSeverity.Error,
            263 => DiagnosticSeverity.Error,
            261 => DiagnosticSeverity.Warning,
            262 => DiagnosticSeverity.Error,
            265 => DiagnosticSeverity.Error,
            266 => DiagnosticSeverity.Warning,
            267 => DiagnosticSeverity.Warning,
            268 => DiagnosticSeverity.Error,
            279 => DiagnosticSeverity.Error,
            269 => DiagnosticSeverity.Warning,
            270 => DiagnosticSeverity.Error,
            271 => DiagnosticSeverity.Error,
            272 => DiagnosticSeverity.Warning,
            273 => DiagnosticSeverity.Error,
            274 => DiagnosticSeverity.Error,
            275 => DiagnosticSeverity.Error,
            276 => DiagnosticSeverity.Error,
            277 => DiagnosticSeverity.Error,
            280 => DiagnosticSeverity.Error,
            281 => DiagnosticSeverity.Error,
            282 => DiagnosticSeverity.Error,
            283 => DiagnosticSeverity.Error,
            301 => DiagnosticSeverity.Error,
            302 => DiagnosticSeverity.Error,
            303 => DiagnosticSeverity.Error,
            304 => DiagnosticSeverity.Error,
            305 => DiagnosticSeverity.Error,
            306 => DiagnosticSeverity.Error,
            307 => DiagnosticSeverity.Warning,
            401 => DiagnosticSeverity.Error,
            _ => null,
        };
    }

    public static DiagnosticSeverity? GetSeverity(string name)
    {
        return name switch
        {
            "UnexpectedCharacter" => DiagnosticSeverity.Error,
            "UnterminatedString" => DiagnosticSeverity.Error,
            "InvalidNumberLiteral" => DiagnosticSeverity.Error,
            "UnterminatedBlockComment" => DiagnosticSeverity.Error,
            "InvalidCharacterLiteral" => DiagnosticSeverity.Error,
            "InvalidEscapeSequence" => DiagnosticSeverity.Error,
            "InvalidUtf8" => DiagnosticSeverity.Error,
            "InvalidControlCharacter" => DiagnosticSeverity.Error,
            "UnexpectedToken" => DiagnosticSeverity.Error,
            "ExpectedExpression" => DiagnosticSeverity.Error,
            "ExpectedStatement" => DiagnosticSeverity.Error,
            "ExpectedTypeName" => DiagnosticSeverity.Error,
            "ExpectedIdentifier" => DiagnosticSeverity.Error,
            "InvalidAssignmentTarget" => DiagnosticSeverity.Error,
            "ExpectedSemicolon" => DiagnosticSeverity.Error,
            "DuplicateVariableClause" => DiagnosticSeverity.Error,
            "SymbolAlreadyDeclared" => DiagnosticSeverity.Error,
            "UndefinedName" => DiagnosticSeverity.Error,
            "UndefinedType" => DiagnosticSeverity.Error,
            "CannotAssignToConstant" => DiagnosticSeverity.Error,
            "TypeMismatch" => DiagnosticSeverity.Error,
            "NotCallable" => DiagnosticSeverity.Error,
            "ArgumentCountMismatch" => DiagnosticSeverity.Error,
            "InvalidLoopControl" => DiagnosticSeverity.Error,
            "InvalidBreakInRepLoop" => DiagnosticSeverity.Error,
            "InvalidYieldUsage" => DiagnosticSeverity.Error,
            "InvalidYieldtoUsage" => DiagnosticSeverity.Error,
            "ReturnValueCountMismatch" => DiagnosticSeverity.Error,
            "ReturnOutsideFunction" => DiagnosticSeverity.Error,
            "InvalidYieldtoTarget" => DiagnosticSeverity.Error,
            "InvalidLocalStorageClass" => DiagnosticSeverity.Error,
            "InvalidExternScope" => DiagnosticSeverity.Error,
            "InvalidParameterStorageClass" => DiagnosticSeverity.Error,
            "PointerStorageClassRequired" => DiagnosticSeverity.Error,
            "UnknownNamedArgument" => DiagnosticSeverity.Error,
            "DuplicateNamedArgument" => DiagnosticSeverity.Error,
            "PositionalArgumentAfterNamed" => DiagnosticSeverity.Error,
            "NamedArgumentConflictsWithPositional" => DiagnosticSeverity.Error,
            "InvalidAddressOfTarget" => DiagnosticSeverity.Error,
            "InvalidExplicitCast" => DiagnosticSeverity.Error,
            "BitcastSizeMismatch" => DiagnosticSeverity.Error,
            "AddressOfRecursiveLocal" => DiagnosticSeverity.Error,
            "MissingReturnValue" => DiagnosticSeverity.Error,
            "ReturnFromCoroutine" => DiagnosticSeverity.Error,
            "FileImportAliasRequired" => DiagnosticSeverity.Error,
            "UnknownNamedModule" => DiagnosticSeverity.Error,
            "ImportFileNotFound" => DiagnosticSeverity.Error,
            "CircularImport" => DiagnosticSeverity.Error,
            "EnumLiteralRequiresContext" => DiagnosticSeverity.Error,
            "BitfieldWidthOverflow" => DiagnosticSeverity.Error,
            "ArrayLiteralRequiresContext" => DiagnosticSeverity.Error,
            "ArrayLiteralSpreadMustBeLast" => DiagnosticSeverity.Error,
            "StructUnknownField" => DiagnosticSeverity.Error,
            "StructMissingFields" => DiagnosticSeverity.Error,
            "StructDuplicateField" => DiagnosticSeverity.Error,
            "StringLengthMismatch" => DiagnosticSeverity.Error,
            "StringToNonConstPointer" => DiagnosticSeverity.Error,
            "ComptimeValueRequired" => DiagnosticSeverity.Error,
            "ComptimeUnsupportedConstruct" => DiagnosticSeverity.Error,
            "ComptimeForbiddenSymbolAccess" => DiagnosticSeverity.Error,
            "ComptimeFuelExhausted" => DiagnosticSeverity.Error,
            "DuplicateNamedModuleRoot" => DiagnosticSeverity.Error,
            "MultiAssignmentRequiresCall" => DiagnosticSeverity.Error,
            "MultiAssignmentTargetCountMismatch" => DiagnosticSeverity.Error,
            "DiscardInExpression" => DiagnosticSeverity.Error,
            "ExternCannotHaveInitializer" => DiagnosticSeverity.Error,
            "MemoryofRequiresVariable" => DiagnosticSeverity.Error,
            "QueryRequiresMemorySpace" => DiagnosticSeverity.Error,
            "QueryUnsupportedType" => DiagnosticSeverity.Error,
            "QueryAutomaticLocal" => DiagnosticSeverity.Error,
            "InvalidMemorySpaceArgument" => DiagnosticSeverity.Error,
            "AssertionFailed" => DiagnosticSeverity.Error,
            "UnknownBuiltin" => DiagnosticSeverity.Error,
            "InvalidPointerArithmetic" => DiagnosticSeverity.Error,
            "IncompatiblePointerSubtraction" => DiagnosticSeverity.Error,
            "ExpressionNotAStatement" => DiagnosticSeverity.Error,
            "RangeIterationRequiresBinding" => DiagnosticSeverity.Error,
            "RangeExpressionOutsideForLoop" => DiagnosticSeverity.Error,
            "ComptimeIntegerTruncation" => DiagnosticSeverity.Warning,
            "AddressOfParameter" => DiagnosticSeverity.Error,
            "AmbiguousLayoutMemberAccess" => DiagnosticSeverity.Error,
            "LexicalNameConflictsWithLayoutMember" => DiagnosticSeverity.Warning,
            "LayoutMemberShadowsParentMember" => DiagnosticSeverity.Warning,
            "TaskLayoutCannotBeInherited" => DiagnosticSeverity.Error,
            "InvalidSpawnTarget" => DiagnosticSeverity.Error,
            "MainTaskMustBeCog" => DiagnosticSeverity.Warning,
            "MissingMainTask" => DiagnosticSeverity.Error,
            "FunctionLayoutSubsetViolation" => DiagnosticSeverity.Error,
            "DuplicateFunctionLayoutMetadata" => DiagnosticSeverity.Warning,
            "DuplicateFunctionAlignMetadata" => DiagnosticSeverity.Error,
            "InvalidFunctionAlignment" => DiagnosticSeverity.Error,
            "TaskLayoutNotAllowedInFunctionMetadata" => DiagnosticSeverity.Error,
            "AccessToForeignLayout" => DiagnosticSeverity.Error,
            "UnsupportedGlobalStorage" => DiagnosticSeverity.Error,
            "InvalidLayoutAlignment" => DiagnosticSeverity.Error,
            "InvalidLayoutAddress" => DiagnosticSeverity.Error,
            "LayoutAddressConflict" => DiagnosticSeverity.Error,
            "LayoutAllocationFailed" => DiagnosticSeverity.Error,
            "InlineAsmUnknownInstruction" => DiagnosticSeverity.Error,
            "InlineAsmUndefinedVariable" => DiagnosticSeverity.Error,
            "InlineAsmEmptyInstruction" => DiagnosticSeverity.Error,
            "InlineAsmInvalidFlagOutput" => DiagnosticSeverity.Error,
            "InlineAsmInvalidInstructionForm" => DiagnosticSeverity.Error,
            "InlineAsmUndefinedLabel" => DiagnosticSeverity.Error,
            "InlineAsmTempReadBeforeWrite" => DiagnosticSeverity.Warning,
            "UnsupportedLowering" => DiagnosticSeverity.Error,
            _ => null,
        };
    }
}

public sealed class UnexpectedCharacterError(SourceText source, TextSpan span, char character)
    : LocatedDiagnosticMessage(source, span, "UnexpectedCharacter", DiagnosticSeverity.Error, 1, $"Unexpected character '{character}'.")
{
    public char Character { get; } = character;
}

public sealed class UnterminatedStringError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "UnterminatedString", DiagnosticSeverity.Error, 2, "Unterminated string literal.")
{
}

public sealed class InvalidNumberLiteralError(SourceText source, TextSpan span, string text)
    : LocatedDiagnosticMessage(source, span, "InvalidNumberLiteral", DiagnosticSeverity.Error, 3, $"Invalid number literal '{text}'.")
{
    public string Text { get; } = text;
}

public sealed class UnterminatedBlockCommentError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "UnterminatedBlockComment", DiagnosticSeverity.Error, 4, "Unterminated block comment.")
{
}

public sealed class InvalidCharacterLiteralError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidCharacterLiteral", DiagnosticSeverity.Error, 5, "Invalid character literal.")
{
}

public sealed class InvalidEscapeSequenceError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidEscapeSequence", DiagnosticSeverity.Error, 6, "Invalid escape sequence.")
{
}

public sealed class InvalidUtf8Error(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidUtf8", DiagnosticSeverity.Error, 7, "Source file is not valid UTF-8.")
{
}

public sealed class InvalidControlCharacterError(SourceText source, TextSpan span, char character)
    : LocatedDiagnosticMessage(source, span, "InvalidControlCharacter", DiagnosticSeverity.Error, 8, $"Control character U+{(int)character:X4} is not allowed in Blade source files.")
{
    public char Character { get; } = character;
}

public sealed class UnexpectedTokenError(SourceText source, TextSpan span, string expected, string actual)
    : LocatedDiagnosticMessage(source, span, "UnexpectedToken", DiagnosticSeverity.Error, 101, $"Expected {expected}, got '{actual}'.")
{
    public string Expected { get; } = expected;
    public string Actual { get; } = actual;
}

public sealed class ExpectedExpressionError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpectedExpression", DiagnosticSeverity.Error, 102, "Expected expression.")
{
}

public sealed class ExpectedStatementError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpectedStatement", DiagnosticSeverity.Error, 103, "Expected statement.")
{
}

public sealed class ExpectedTypeNameError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpectedTypeName", DiagnosticSeverity.Error, 104, "Expected type name.")
{
}

public sealed class ExpectedIdentifierError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpectedIdentifier", DiagnosticSeverity.Error, 105, "Expected identifier.")
{
}

public sealed class InvalidAssignmentTargetError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidAssignmentTarget", DiagnosticSeverity.Error, 106, "Invalid assignment target.")
{
}

public sealed class ExpectedSemicolonError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpectedSemicolon", DiagnosticSeverity.Error, 107, "Expected ';'.")
{
}

public sealed class DuplicateVariableClauseError(SourceText source, TextSpan span, string clauseName)
    : LocatedDiagnosticMessage(source, span, "DuplicateVariableClause", DiagnosticSeverity.Error, 108, $"Duplicate variable clause '{clauseName}'.")
{
    public string ClauseName { get; } = clauseName;
}

public sealed class SymbolAlreadyDeclaredError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "SymbolAlreadyDeclared", DiagnosticSeverity.Error, 201, $"Symbol '{name}' is already declared.")
{
    public string ParameterName { get; } = name;
}

public sealed class UndefinedNameError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "UndefinedName", DiagnosticSeverity.Error, 202, $"Name '{name}' does not exist in the current scope.")
{
    public string ParameterName { get; } = name;
}

public sealed class UndefinedTypeError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "UndefinedType", DiagnosticSeverity.Error, 203, $"Type '{name}' is not defined.")
{
    public string ParameterName { get; } = name;
}

public sealed class CannotAssignToConstantError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "CannotAssignToConstant", DiagnosticSeverity.Error, 204, $"Cannot assign to constant '{name}'.")
{
    public string ParameterName { get; } = name;
}

public sealed class TypeMismatchError(SourceText source, TextSpan span, string expected, string actual)
    : LocatedDiagnosticMessage(source, span, "TypeMismatch", DiagnosticSeverity.Error, 205, $"Type mismatch: expected '{expected}', got '{actual}'.")
{
    public string Expected { get; } = expected;
    public string Actual { get; } = actual;
}

public sealed class NotCallableError(SourceText source, TextSpan span, string typeName)
    : LocatedDiagnosticMessage(source, span, "NotCallable", DiagnosticSeverity.Error, 206, $"Expression of type '{typeName}' is not callable.")
{
    public string TypeName { get; } = typeName;
}

public sealed class ArgumentCountMismatchError(SourceText source, TextSpan span, string functionName, int expected, int actual)
    : LocatedDiagnosticMessage(source, span, "ArgumentCountMismatch", DiagnosticSeverity.Error, 207, $"Function '{functionName}' expects {expected} argument(s), but got {actual}.")
{
    public string FunctionName { get; } = functionName;
    public int Expected { get; } = expected;
    public int Actual { get; } = actual;
}

public sealed class InvalidLoopControlError(SourceText source, TextSpan span, string keyword)
    : LocatedDiagnosticMessage(source, span, "InvalidLoopControl", DiagnosticSeverity.Error, 208, $"'{keyword}' can only be used inside a loop.")
{
    public string Keyword { get; } = keyword;
}

public sealed class InvalidBreakInRepLoopError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidBreakInRepLoop", DiagnosticSeverity.Error, 209, "'break' is not allowed inside 'rep' loops.")
{
}

public sealed class InvalidYieldUsageError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidYieldUsage", DiagnosticSeverity.Error, 210, "'yield' is only allowed inside int1/int2/int3 functions.")
{
}

public sealed class InvalidYieldtoUsageError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidYieldtoUsage", DiagnosticSeverity.Error, 211, "'yieldto' is not allowed in this context.")
{
}

public sealed class ReturnValueCountMismatchError(SourceText source, TextSpan span, string functionName, int expected, int actual)
    : LocatedDiagnosticMessage(source, span, "ReturnValueCountMismatch", DiagnosticSeverity.Error, 212, $"Function '{functionName}' returns {expected} value(s), but got {actual}.")
{
    public string FunctionName { get; } = functionName;
    public int Expected { get; } = expected;
    public int Actual { get; } = actual;
}

public sealed class ReturnOutsideFunctionError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ReturnOutsideFunction", DiagnosticSeverity.Error, 213, "'return' is only allowed inside a function.")
{
}

public sealed class InvalidYieldtoTargetError(SourceText source, TextSpan span, string target)
    : LocatedDiagnosticMessage(source, span, "InvalidYieldtoTarget", DiagnosticSeverity.Error, 214, $"'{target}' is not a coroutine function.")
{
    public string Target { get; } = target;
}

public sealed class InvalidLocalStorageClassError(SourceText source, TextSpan span, string storageClass)
    : LocatedDiagnosticMessage(source, span, "InvalidLocalStorageClass", DiagnosticSeverity.Error, 215, $"Storage class '{storageClass}' is only allowed for top-level storage declarations.")
{
    public string StorageClass { get; } = storageClass;
}

public sealed class InvalidExternScopeError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidExternScope", DiagnosticSeverity.Error, 216, "automatic variable cannot be extern")
{
}

public sealed class InvalidParameterStorageClassError(SourceText source, TextSpan span, string storageClass)
    : LocatedDiagnosticMessage(source, span, "InvalidParameterStorageClass", DiagnosticSeverity.Error, 217, $"Parameter storage class '{storageClass}' is not supported.")
{
    public string StorageClass { get; } = storageClass;
}

public sealed class PointerStorageClassRequiredError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "PointerStorageClassRequired", DiagnosticSeverity.Error, 264, "Pointer types must explicitly declare a storage class.")
{
}

public sealed class UnknownNamedArgumentError(SourceText source, TextSpan span, string functionName, string parameterName)
    : LocatedDiagnosticMessage(source, span, "UnknownNamedArgument", DiagnosticSeverity.Error, 219, $"Function '{functionName}' does not have a parameter named '{parameterName}'.")
{
    public string FunctionName { get; } = functionName;
    public string ParameterName { get; } = parameterName;
}

public sealed class DuplicateNamedArgumentError(SourceText source, TextSpan span, string parameterName)
    : LocatedDiagnosticMessage(source, span, "DuplicateNamedArgument", DiagnosticSeverity.Error, 220, $"Named argument '{parameterName}' is specified more than once.")
{
    public string ParameterName { get; } = parameterName;
}

public sealed class PositionalArgumentAfterNamedError(SourceText source, TextSpan span, string functionName)
    : LocatedDiagnosticMessage(source, span, "PositionalArgumentAfterNamed", DiagnosticSeverity.Error, 221, $"Function '{functionName}' does not allow positional arguments after named arguments.")
{
    public string FunctionName { get; } = functionName;
}

public sealed class NamedArgumentConflictsWithPositionalError(SourceText source, TextSpan span, string parameterName)
    : LocatedDiagnosticMessage(source, span, "NamedArgumentConflictsWithPositional", DiagnosticSeverity.Error, 222, $"Named argument '{parameterName}' conflicts with a positional argument.")
{
    public string ParameterName { get; } = parameterName;
}

public sealed class InvalidAddressOfTargetError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidAddressOfTarget", DiagnosticSeverity.Error, 223, "Address-of requires an addressable variable or parameter.")
{
}

public sealed class InvalidExplicitCastError(SourceText source, TextSpan span, string sourceType, string targetType)
    : LocatedDiagnosticMessage(source, span, "InvalidExplicitCast", DiagnosticSeverity.Error, 224, $"Cannot explicitly cast from '{sourceType}' to '{targetType}'.")
{
    public string SourceType { get; } = sourceType;
    public string TargetType { get; } = targetType;
}

public sealed class BitcastSizeMismatchError(SourceText source, TextSpan span, string sourceType, string targetType)
    : LocatedDiagnosticMessage(source, span, "BitcastSizeMismatch", DiagnosticSeverity.Error, 225, $"Cannot bitcast from '{sourceType}' to '{targetType}' because their sizes differ.")
{
    public string SourceType { get; } = sourceType;
    public string TargetType { get; } = targetType;
}

public sealed class AddressOfRecursiveLocalError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "AddressOfRecursiveLocal", DiagnosticSeverity.Error, 226, $"Cannot take the address of local '{name}' inside a recursive function.")
{
    public string ParameterName { get; } = name;
}

public sealed class MissingReturnValueError(SourceText source, TextSpan span, string functionName)
    : LocatedDiagnosticMessage(source, span, "MissingReturnValue", DiagnosticSeverity.Error, 227, $"Function '{functionName}' must return a value on all control-flow paths.")
{
    public string FunctionName { get; } = functionName;
}

public sealed class ReturnFromCoroutineError(SourceText source, TextSpan span, string functionName)
    : LocatedDiagnosticMessage(source, span, "ReturnFromCoroutine", DiagnosticSeverity.Error, 278, $"Coroutine function '{functionName}' cannot return and must end in 'yieldto' on every control-flow path.")
{
    public string FunctionName { get; } = functionName;
}

public sealed class FileImportAliasRequiredError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "FileImportAliasRequired", DiagnosticSeverity.Error, 228, "File imports require an alias: use 'import \"path\" as alias;'.")
{
}

public sealed class UnknownNamedModuleError(SourceText source, TextSpan span, string moduleName)
    : LocatedDiagnosticMessage(source, span, "UnknownNamedModule", DiagnosticSeverity.Error, 229, $"Named module '{moduleName}' is not defined.")
{
    public string ModuleName { get; } = moduleName;
}

public sealed class ImportFileNotFoundError(SourceText source, TextSpan span, string path)
    : LocatedDiagnosticMessage(source, span, "ImportFileNotFound", DiagnosticSeverity.Error, 230, $"Imported file '{path}' was not found.")
{
    public string Path { get; } = path;
}

public sealed class CircularImportError(SourceText source, TextSpan span, string path)
    : LocatedDiagnosticMessage(source, span, "CircularImport", DiagnosticSeverity.Error, 231, $"Circular import detected at '{path}'.")
{
    public string Path { get; } = path;
}

public sealed class EnumLiteralRequiresContextError(SourceText source, TextSpan span, string memberName)
    : LocatedDiagnosticMessage(source, span, "EnumLiteralRequiresContext", DiagnosticSeverity.Error, 232, $"Enum literal '.{memberName}' requires an expected enum type.")
{
    public string MemberName { get; } = memberName;
}

public sealed class BitfieldWidthOverflowError(SourceText source, TextSpan span, string bitfieldName, string fieldName, int usedBits, int backingBits)
    : LocatedDiagnosticMessage(source, span, "BitfieldWidthOverflow", DiagnosticSeverity.Error, 233, $"Bitfield '{bitfieldName}' field '{fieldName}' uses {usedBits} bits, exceeding backing width {backingBits}.")
{
    public string BitfieldName { get; } = bitfieldName;
    public string FieldName { get; } = fieldName;
    public int UsedBits { get; } = usedBits;
    public int BackingBits { get; } = backingBits;
}

public sealed class ArrayLiteralRequiresContextError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ArrayLiteralRequiresContext", DiagnosticSeverity.Error, 234, "Array literal requires an expected array type.")
{
}

public sealed class ArrayLiteralSpreadMustBeLastError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ArrayLiteralSpreadMustBeLast", DiagnosticSeverity.Error, 235, "Array literal spread element must be the last element.")
{
}

public sealed class StructUnknownFieldError(SourceText source, TextSpan span, string structName, string fieldName)
    : LocatedDiagnosticMessage(source, span, "StructUnknownField", DiagnosticSeverity.Error, 236, $"Struct '{structName}' does not have a field named '{fieldName}'.")
{
    public string StructName { get; } = structName;
    public string FieldName { get; } = fieldName;
}

public sealed class StructMissingFieldsError(SourceText source, TextSpan span, string structName, string missingFields)
    : LocatedDiagnosticMessage(source, span, "StructMissingFields", DiagnosticSeverity.Error, 237, $"Struct literal for '{structName}' is missing field(s): {missingFields}.")
{
    public string StructName { get; } = structName;
    public string MissingFields { get; } = missingFields;
}

public sealed class StructDuplicateFieldError(SourceText source, TextSpan span, string fieldName)
    : LocatedDiagnosticMessage(source, span, "StructDuplicateField", DiagnosticSeverity.Error, 238, $"Field '{fieldName}' is specified more than once.")
{
    public string FieldName { get; } = fieldName;
}

public sealed class StringLengthMismatchError(SourceText source, TextSpan span, int expectedLength, int actualLength)
    : LocatedDiagnosticMessage(source, span, "StringLengthMismatch", DiagnosticSeverity.Error, 239, $"String length {actualLength} does not match array length {expectedLength}.")
{
    public int ExpectedLength { get; } = expectedLength;
    public int ActualLength { get; } = actualLength;
}

public sealed class StringToNonConstPointerError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "StringToNonConstPointer", DiagnosticSeverity.Error, 240, "String literal cannot be assigned to a non-const pointer.")
{
}

public sealed class ComptimeValueRequiredError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ComptimeValueRequired", DiagnosticSeverity.Error, 241, "Expression must be compile-time evaluable in this context.")
{
}

public sealed class ComptimeUnsupportedConstructError(SourceText source, TextSpan span, string detail)
    : LocatedDiagnosticMessage(source, span, "ComptimeUnsupportedConstruct", DiagnosticSeverity.Error, 242, $"Construct is not supported during comptime evaluation: {detail}")
{
    public string Detail { get; } = detail;
}

public sealed class ComptimeForbiddenSymbolAccessError(SourceText source, TextSpan span, string detail)
    : LocatedDiagnosticMessage(source, span, "ComptimeForbiddenSymbolAccess", DiagnosticSeverity.Error, 243, $"Comptime evaluation cannot access this symbol: {detail}")
{
    public string Detail { get; } = detail;
}

public sealed class ComptimeFuelExhaustedError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ComptimeFuelExhausted", DiagnosticSeverity.Error, 244, "Comptime evaluation ran out of fuel.")
{
}

public sealed class DuplicateNamedModuleRootError(SourceText source, TextSpan span, string firstModuleName, string secondModuleName, string path)
    : LocatedDiagnosticMessage(source, span, "DuplicateNamedModuleRoot", DiagnosticSeverity.Error, 245, $"Named modules '{firstModuleName}' and '{secondModuleName}' both resolve to '{path}'.")
{
    public string FirstModuleName { get; } = firstModuleName;
    public string SecondModuleName { get; } = secondModuleName;
    public string Path { get; } = path;
}

public sealed class MultiAssignmentRequiresCallError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "MultiAssignmentRequiresCall", DiagnosticSeverity.Error, 246, "Multi-target assignment requires a function call or spawn expression on the right-hand side.")
{
}

public sealed class MultiAssignmentTargetCountMismatchError(SourceText source, TextSpan span, string expressionName, int expected, int actual)
    : LocatedDiagnosticMessage(source, span, "MultiAssignmentTargetCountMismatch", DiagnosticSeverity.Error, 247, $"Expression '{expressionName}' returns {expected} value(s), but {actual} assignment target(s) provided.")
{
    public string ExpressionName { get; } = expressionName;
    public int Expected { get; } = expected;
    public int Actual { get; } = actual;
}

public sealed class DiscardInExpressionError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "DiscardInExpression", DiagnosticSeverity.Error, 248, "The discard '_' can only be used as an assignment target.")
{
}

public sealed class ExternCannotHaveInitializerError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "ExternCannotHaveInitializer", DiagnosticSeverity.Error, 249, $"Extern variable '{name}' cannot have an initializer.")
{
    public string ParameterName { get; } = name;
}

public sealed class MemoryofRequiresVariableError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "MemoryofRequiresVariable", DiagnosticSeverity.Error, 250, "'memoryof' requires a variable declaration, not a type.")
{
}

public sealed class QueryRequiresMemorySpaceError(SourceText source, TextSpan span, string operatorName)
    : LocatedDiagnosticMessage(source, span, "QueryRequiresMemorySpace", DiagnosticSeverity.Error, 251, $"'{operatorName}' of a type requires a memory space argument.")
{
    public string OperatorName { get; } = operatorName;
}

public sealed class QueryUnsupportedTypeError(SourceText source, TextSpan span, string operatorName, string typeName)
    : LocatedDiagnosticMessage(source, span, "QueryUnsupportedType", DiagnosticSeverity.Error, 252, $"Cannot determine size/alignment for type '{typeName}' in '{operatorName}'.")
{
    public string OperatorName { get; } = operatorName;
    public string TypeName { get; } = typeName;
}

public sealed class QueryAutomaticLocalError(SourceText source, TextSpan span, string operatorName, string variableName)
    : LocatedDiagnosticMessage(source, span, "QueryAutomaticLocal", DiagnosticSeverity.Error, 253, $"'{operatorName}' cannot be applied to automatic local variable '{variableName}'.")
{
    public string OperatorName { get; } = operatorName;
    public string VariableName { get; } = variableName;
}

public sealed class InvalidMemorySpaceArgumentError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InvalidMemorySpaceArgument", DiagnosticSeverity.Error, 254, "Expected a 'builtin.MemorySpace' value.")
{
}

public sealed class AssertionFailedError(SourceText source, TextSpan span, string assertionMessage)
    : LocatedDiagnosticMessage(source, span, "AssertionFailed", DiagnosticSeverity.Error, 255, $"{assertionMessage}")
{
    public string AssertionMessage { get; } = assertionMessage;
}

public sealed class UnknownBuiltinError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "UnknownBuiltin", DiagnosticSeverity.Error, 256, $"Unknown builtin '@{name}'.")
{
    public string ParameterName { get; } = name;
}

public sealed class InvalidPointerArithmeticError(SourceText source, TextSpan span, string operation)
    : LocatedDiagnosticMessage(source, span, "InvalidPointerArithmetic", DiagnosticSeverity.Error, 257, $"Invalid pointer arithmetic for '{operation}'. Only '[*]' pointers support '+', '-', '+=', and '-=' with integer deltas.")
{
    public string Operation { get; } = operation;
}

public sealed class IncompatiblePointerSubtractionError(SourceText source, TextSpan span, string leftType, string rightType)
    : LocatedDiagnosticMessage(source, span, "IncompatiblePointerSubtraction", DiagnosticSeverity.Error, 258, $"Pointer subtraction requires matching '[*]' pointer element types and memory spaces, but got '{leftType}' and '{rightType}'.")
{
    public string LeftType { get; } = leftType;
    public string RightType { get; } = rightType;
}

public sealed class ExpressionNotAStatementError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "ExpressionNotAStatement", DiagnosticSeverity.Error, 259, "An expression is not a statement. Only function calls and spawn expressions are allowed as standalone statements.")
{
}

public sealed class RangeIterationRequiresBindingError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "RangeIterationRequiresBinding", DiagnosticSeverity.Error, 260, "Range iteration requires an index binding '-> index'.")
{
}

public sealed class RangeExpressionOutsideForLoopError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "RangeExpressionOutsideForLoop", DiagnosticSeverity.Error, 263, "Range expressions are only allowed as the iterable of a for/rep for statement.")
{
}

public sealed class ComptimeIntegerTruncationWarning(SourceText source, TextSpan span, string value, string targetType, string truncatedValue)
    : LocatedDiagnosticMessage(source, span, "ComptimeIntegerTruncation", DiagnosticSeverity.Warning, 261, $"Compile-time integer value {value} is truncated to {truncatedValue} when converted to '{targetType}'.")
{
    public string Value { get; } = value;
    public string TargetType { get; } = targetType;
    public string TruncatedValue { get; } = truncatedValue;
}

public sealed class AddressOfParameterError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "AddressOfParameter", DiagnosticSeverity.Error, 262, $"Cannot take the address of parameter '{name}'.")
{
    public string ParameterName { get; } = name;
}

public sealed class AmbiguousLayoutMemberAccessError(SourceText source, TextSpan span, string name, string layoutNamesText)
    : LocatedDiagnosticMessage(source, span, "AmbiguousLayoutMemberAccess", DiagnosticSeverity.Error, 265, $"Name '{name}' is provided by multiple layouts ({layoutNamesText}). Use 'Layout.member' to disambiguate.")
{
    public string ParameterName { get; } = name;
    public string LayoutNamesText { get; } = layoutNamesText;
}

public sealed class LexicalNameConflictsWithLayoutMemberWarning(SourceText source, TextSpan span, string name, string layoutNamesText)
    : LocatedDiagnosticMessage(source, span, "LexicalNameConflictsWithLayoutMember", DiagnosticSeverity.Warning, 266, $"Name '{name}' is visible both lexically and through layout members ({layoutNamesText}). The lexical name wins.")
{
    public string ParameterName { get; } = name;
    public string LayoutNamesText { get; } = layoutNamesText;
}

public sealed class LayoutMemberShadowsParentMemberWarning(SourceText source, TextSpan span, string layoutName, string memberName)
    : LocatedDiagnosticMessage(source, span, "LayoutMemberShadowsParentMember", DiagnosticSeverity.Warning, 267, $"Layout '{layoutName}' declares member '{memberName}', which shadows an inherited layout member.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
}

public sealed class TaskLayoutCannotBeInheritedError(SourceText source, TextSpan span, string taskName)
    : LocatedDiagnosticMessage(source, span, "TaskLayoutCannotBeInherited", DiagnosticSeverity.Error, 268, $"Task layout '{taskName}' cannot be inherited.")
{
    public string TaskName { get; } = taskName;
}

public sealed class InvalidSpawnTargetError(SourceText source, TextSpan span, string targetName)
    : LocatedDiagnosticMessage(source, span, "InvalidSpawnTarget", DiagnosticSeverity.Error, 279, $"Spawn target '{targetName}' is not a task.")
{
    public string TargetName { get; } = targetName;
}

public sealed class MainTaskMustBeCogWarning(SourceText source, TextSpan span, string taskName, string storageClassKeyword)
    : LocatedDiagnosticMessage(source, span, "MainTaskMustBeCog", DiagnosticSeverity.Warning, 269, $"Entry task '{taskName}' should be declared as 'cog task'; found '{storageClassKeyword} task'.")
{
    public string TaskName { get; } = taskName;
    public string StorageClassKeyword { get; } = storageClassKeyword;
}

public sealed class MissingMainTaskError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "MissingMainTask", DiagnosticSeverity.Error, 270, "Root module must export a task named 'main'.")
{
}

public sealed class FunctionLayoutSubsetViolationError(SourceText source, TextSpan span, string callerName, string calleeName, string callerLayoutText, string calleeLayoutText)
    : LocatedDiagnosticMessage(source, span, "FunctionLayoutSubsetViolation", DiagnosticSeverity.Error, 271, $"Function '{callerName}' cannot transfer control to '{calleeName}' because callee layouts [{calleeLayoutText}] are not a subset of caller layouts [{callerLayoutText}].")
{
    public string CallerName { get; } = callerName;
    public string CalleeName { get; } = calleeName;
    public string CallerLayoutText { get; } = callerLayoutText;
    public string CalleeLayoutText { get; } = calleeLayoutText;
}

public sealed class DuplicateFunctionLayoutMetadataWarning(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "DuplicateFunctionLayoutMetadata", DiagnosticSeverity.Warning, 272, "Duplicate function metadata property 'layout(...)'; layouts are merged.")
{
}

public sealed class DuplicateFunctionAlignMetadataError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "DuplicateFunctionAlignMetadata", DiagnosticSeverity.Error, 273, "Duplicate function metadata property 'align(...)'.")
{
}

public sealed class InvalidFunctionAlignmentError(SourceText source, TextSpan span, int alignment)
    : LocatedDiagnosticMessage(source, span, "InvalidFunctionAlignment", DiagnosticSeverity.Error, 274, $"Function alignment must be a positive power of two; got '{alignment}'.")
{
    public int Alignment { get; } = alignment;
}

public sealed class TaskLayoutNotAllowedInFunctionMetadataError(SourceText source, TextSpan span, string taskName)
    : LocatedDiagnosticMessage(source, span, "TaskLayoutNotAllowedInFunctionMetadata", DiagnosticSeverity.Error, 275, $"Task layout '{taskName}' cannot be referenced from function metadata.")
{
    public string TaskName { get; } = taskName;
}

public sealed class AccessToForeignLayoutError(SourceText source, TextSpan span, string layoutName, string memberName)
    : LocatedDiagnosticMessage(source, span, "AccessToForeignLayout", DiagnosticSeverity.Error, 276, $"Layout member '{layoutName}.{memberName}' is not accessible from this context because the layout is not declared here.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
}

public sealed class UnsupportedGlobalStorageError(SourceText source, TextSpan span, string storageClass)
    : LocatedDiagnosticMessage(source, span, "UnsupportedGlobalStorage", DiagnosticSeverity.Error, 277, $"Top-level global storage class '{storageClass}' is not supported here. Use 'hub' or move the declaration into a layout.")
{
    public string StorageClass { get; } = storageClass;
}

public sealed class InvalidLayoutAlignmentError(SourceText source, TextSpan span, string layoutName, string memberName, int alignment)
    : LocatedDiagnosticMessage(source, span, "InvalidLayoutAlignment", DiagnosticSeverity.Error, 280, $"Layout member '{layoutName}.{memberName}' has invalid alignment '{alignment}'. Alignment must be a positive power of two.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
    public int Alignment { get; } = alignment;
}

public sealed class InvalidLayoutAddressError(SourceText source, TextSpan span, string layoutName, string memberName, string storageName, int address, int sizeInAddressUnits)
    : LocatedDiagnosticMessage(source, span, "InvalidLayoutAddress", DiagnosticSeverity.Error, 281, $"Layout member '{layoutName}.{memberName}' cannot be placed at {storageName} address '{address}' with size '{sizeInAddressUnits}'.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
    public string StorageName { get; } = storageName;
    public int Address { get; } = address;
    public int SizeInAddressUnits { get; } = sizeInAddressUnits;
}

public sealed class LayoutAddressConflictError(SourceText source, TextSpan span, string layoutName, string memberName, string storageName, int address, string conflictingLayoutName, string conflictingMemberName, int conflictingAddress)
    : LocatedDiagnosticMessage(source, span, "LayoutAddressConflict", DiagnosticSeverity.Error, 282, $"Layout member '{layoutName}.{memberName}' at {storageName} address '{address}' overlaps '{conflictingLayoutName}.{conflictingMemberName}' at address '{conflictingAddress}'.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
    public string StorageName { get; } = storageName;
    public int Address { get; } = address;
    public string ConflictingLayoutName { get; } = conflictingLayoutName;
    public string ConflictingMemberName { get; } = conflictingMemberName;
    public int ConflictingAddress { get; } = conflictingAddress;
}

public sealed class LayoutAllocationFailedError(SourceText source, TextSpan span, string layoutName, string memberName, string storageName, int sizeInAddressUnits, int alignmentInAddressUnits)
    : LocatedDiagnosticMessage(source, span, "LayoutAllocationFailed", DiagnosticSeverity.Error, 283, $"Layout solver could not place '{layoutName}.{memberName}' in {storageName} space with size '{sizeInAddressUnits}' and alignment '{alignmentInAddressUnits}'.")
{
    public string LayoutName { get; } = layoutName;
    public string MemberName { get; } = memberName;
    public string StorageName { get; } = storageName;
    public int SizeInAddressUnits { get; } = sizeInAddressUnits;
    public int AlignmentInAddressUnits { get; } = alignmentInAddressUnits;
}

public sealed class InlineAsmUnknownInstructionError(SourceText source, TextSpan span, string mnemonic)
    : LocatedDiagnosticMessage(source, span, "InlineAsmUnknownInstruction", DiagnosticSeverity.Error, 301, $"Unknown P2 instruction '{mnemonic}' in inline assembly.")
{
    public string Mnemonic { get; } = mnemonic;
}

public sealed class InlineAsmUndefinedVariableError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "InlineAsmUndefinedVariable", DiagnosticSeverity.Error, 302, $"Undefined variable '{name}' referenced in inline assembly.")
{
    public string ParameterName { get; } = name;
}

public sealed class InlineAsmEmptyInstructionError(SourceText source, TextSpan span)
    : LocatedDiagnosticMessage(source, span, "InlineAsmEmptyInstruction", DiagnosticSeverity.Error, 303, "Empty instruction in inline assembly block.")
{
}

public sealed class InlineAsmInvalidFlagOutputError(SourceText source, TextSpan span, string flag)
    : LocatedDiagnosticMessage(source, span, "InlineAsmInvalidFlagOutput", DiagnosticSeverity.Error, 304, $"Invalid flag output '@{flag}' in inline assembly. Expected '@C' or '@Z'.")
{
    public string Flag { get; } = flag;
}

public sealed class InlineAsmInvalidInstructionFormError(SourceText source, TextSpan span, string mnemonic, int operandCount)
    : LocatedDiagnosticMessage(source, span, "InlineAsmInvalidInstructionForm", DiagnosticSeverity.Error, 305, $"Instruction '{mnemonic}' does not support {operandCount} operand(s) in inline assembly.")
{
    public string Mnemonic { get; } = mnemonic;
    public int OperandCount { get; } = operandCount;
}

public sealed class InlineAsmUndefinedLabelError(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "InlineAsmUndefinedLabel", DiagnosticSeverity.Error, 306, $"Inline assembly references undefined label '{name}'. Only labels defined within the same asm block are accessible.")
{
    public string ParameterName { get; } = name;
}

public sealed class InlineAsmTempReadBeforeWriteWarning(SourceText source, TextSpan span, string name)
    : LocatedDiagnosticMessage(source, span, "InlineAsmTempReadBeforeWrite", DiagnosticSeverity.Warning, 307, $"Inline assembly temporary '{name}' is read before any prior write in the same asm block. The register contents are unspecified.")
{
    public string ParameterName { get; } = name;
}

public sealed class UnsupportedLoweringError(SourceText source, TextSpan span, string lowering)
    : LocatedDiagnosticMessage(source, span, "UnsupportedLowering", DiagnosticSeverity.Error, 401, $"Backend lowering for '{lowering}' is not implemented yet.")
{
    public string Lowering { get; } = lowering;
}

