

all: compile load

compile:
    flexspin \
        -2 \
        -b \
        -Wall \
        -Wabs-paths \
        -o envelope.bin \
        envelope.spin2 

load:
    loadp2 \
        -v \
        -p /dev/ttyUSB0 \
        -t envelope.bin