using System;
using System.IO;
using System.Linq;
using System.Text;

namespace Blade.DiagnosticGen;

/// <summary>
/// Command-line entry point for generating typed diagnostic message classes.
/// </summary>
public static class Program
{
    /// <summary>
    /// Runs the diagnostic generator with an input definition file and output C# file.
    /// </summary>
    public static int Main(string[] args)
    {
        ArgumentNullException.ThrowIfNull(args);

        if (args.Length != 2)
        {
            Console.Error.WriteLine("diag-gen <input> <output>");
            return 1;
        }

        string[] lines = File.ReadAllLines(args[0], Encoding.UTF8);
        Model model = Model.Parse(lines);

        string? outputDirectory = Path.GetDirectoryName(Path.GetFullPath(args[1]));
        if (!string.IsNullOrEmpty(outputDirectory))
            Directory.CreateDirectory(outputDirectory);

        using StreamWriter writer = new(args[1], append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        GenerateCode(writer, model);
        return 0;
    }

    /// <summary>
    /// Writes generated C# diagnostic message classes for the supplied parsed model.
    /// </summary>
    public static void GenerateCode(TextWriter writer, Model model)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(model);

        writer.WriteLine("//");
        writer.WriteLine("// AUTOGENERATED CODE. DO NOT EDIT MANUALLY.");
        writer.WriteLine("// REFER TO Tools/Blade.DiagnosticGen/Program.cs TO EDIT FILE.");
        writer.WriteLine("//");
        writer.WriteLine("#nullable enable");
        writer.WriteLine();
        foreach (string decl in model.Usings.OrderBy(static item => item))
        {
            writer.WriteLine("using {0};", decl);
        }

        writer.WriteLine();
        writer.WriteLine("namespace Blade.Diagnostics;");
        writer.WriteLine();

        WriteLookupHelpers(writer, model);

        foreach (Message message in model.Messages)
        {
            WriteMessageClass(writer, message);
        }
    }

    private static void WriteMessageClass(TextWriter writer, Message message)
    {
        string baseClass = message.Kind == MessageKind.Located
            ? "LocatedDiagnosticMessage"
            : "DiagnosticMessage";
        string ctorParameters = GetConstructorParameters(message);
        string baseArguments = GetBaseArguments(message);

        writer.WriteLine("public sealed class {0}({1})", message.ClassName, ctorParameters);
        writer.WriteLine("    : {0}({1})", baseClass, baseArguments);
        writer.WriteLine("{");
        if (message.Kind == MessageKind.Generic)
        {
            writer.WriteLine("    public override bool IsLocated => false;");
            if (message.Parameters.Count > 0)
                writer.WriteLine();
        }

        foreach (MessageParameter parameter in message.Parameters)
        {
            writer.WriteLine("    public {0} {1} {{ get; }} = {2};", parameter.Type, ToPropertyName(parameter.Name), parameter.Name);
        }

        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static string GetConstructorParameters(Message message)
    {
        string parameters = string.Join(
            ", ",
            message.Parameters.Select(static parameter => parameter.Type + " " + parameter.Name));
        if (message.Kind == MessageKind.Generic)
            return parameters;
        if (string.IsNullOrWhiteSpace(parameters))
            return "SourceText source, TextSpan span";
        return "SourceText source, TextSpan span, " + parameters;
    }

    private static string GetBaseArguments(Message message)
    {
        string common = "\"" + message.Name + "\", "
            + GetSeverityExpression(message)
            + ", "
            + GetNumericCode(message).ToString(System.Globalization.CultureInfo.InvariantCulture)
            + ", "
            + message.Text.Expression;
        if (message.Kind == MessageKind.Generic)
            return common;
        return "source, span, " + common;
    }

    private static void WriteLookupHelpers(TextWriter writer, Model model)
    {
        writer.WriteLine("public abstract partial class DiagnosticMessage");
        writer.WriteLine("{");
        writer.WriteLine("    public static (DiagnosticSeverity severity, int code)? GetByName(string name)");
        writer.WriteLine("    {");
        writer.WriteLine("        return name switch");
        writer.WriteLine("        {");
        foreach (Message message in model.Messages)
        {
            writer.WriteLine(
                "            \"{0}\" => ({1}, {2}),",
                message.Name,
                GetSeverityExpression(message),
                GetNumericCode(message).ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        writer.WriteLine("            _ => null,");
        writer.WriteLine("        };");
        writer.WriteLine("    }");
        writer.WriteLine();
        writer.WriteLine("    public static string? GetNameFrom(int code)");
        writer.WriteLine("    {");
        writer.WriteLine("        return code switch");
        writer.WriteLine("        {");
        foreach (Message message in model.Messages)
        {
            writer.WriteLine("            {0} => \"{1}\",", GetNumericCode(message).ToString(System.Globalization.CultureInfo.InvariantCulture), message.Name);
        }

        writer.WriteLine("            _ => null,");
        writer.WriteLine("        };");
        writer.WriteLine("    }");
        writer.WriteLine();
        writer.WriteLine("    public static DiagnosticSeverity? GetSeverity(int code)");
        writer.WriteLine("    {");
        writer.WriteLine("        return code switch");
        writer.WriteLine("        {");
        foreach (Message message in model.Messages)
        {
            writer.WriteLine("            {0} => {1},", GetNumericCode(message).ToString(System.Globalization.CultureInfo.InvariantCulture), GetSeverityExpression(message));
        }

        writer.WriteLine("            _ => null,");
        writer.WriteLine("        };");
        writer.WriteLine("    }");
        writer.WriteLine();
        writer.WriteLine("    public static DiagnosticSeverity? GetSeverity(string name)");
        writer.WriteLine("    {");
        writer.WriteLine("        return name switch");
        writer.WriteLine("        {");
        foreach (Message message in model.Messages)
        {
            writer.WriteLine("            \"{0}\" => {1},", message.Name, GetSeverityExpression(message));
        }

        writer.WriteLine("            _ => null,");
        writer.WriteLine("        };");
        writer.WriteLine("    }");
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private static string GetSeverityExpression(Message message)
    {
        return message.Code[0] switch
        {
            'E' => "DiagnosticSeverity.Error",
            'W' => "DiagnosticSeverity.Warning",
            'I' => "DiagnosticSeverity.Note",
            _ => throw new InvalidOperationException("Validated diagnostic codes must start with E, W, or I."),
        };
    }

    private static int GetNumericCode(Message message)
    {
        return int.Parse(message.Code[1..], System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string ToPropertyName(string name)
    {
        string propertyName = ToPascalCase(name);
        return propertyName switch
        {
            "Code" => "DiagnosticCode",
            "IsLocated" => "DiagnosticIsLocated",
            "Message" => "DiagnosticMessageText",
            "Name" => "ParameterName",
            "Severity" => "DiagnosticSeverity",
            _ => propertyName,
        };
    }

    private static string ToPascalCase(string name)
    {
        if (name.Length == 0)
            return name;
        if (name.Length == 1)
            return char.ToUpperInvariant(name[0]).ToString();
        return char.ToUpperInvariant(name[0]) + name[1..];
    }
}
